FROM node:alpine

WORKDIR /app

EXPOSE 5173

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]